### PR TITLE
refactored LineFinder::drawDetectedLines

### PR DESCRIPTION
**Pull request by Red-Portal**
This should work

### CODE REVIEW

**Comment by chi3236** [comment]
Please explain us why this modified code is better than the original code.
I could not find any functional improvement or performance improvement after applying your code.

**Comment by zappybiby** [comment]
So "refactoring" means to restructure the code in order to make it easier to read. In this way, refactored code should not change performance or function, but instead remove confusion and enhance readability.

Honestly, I don't know what this piece of particular code is supposed to do, so I can't confirm it does not change anything functionally. But if you didn't notice a change in performance/function then that means that @Red-Portal simply refactored the code.

**Comment by chi3236** [comment]
Oops, I wrote really stupid comment. I proved that the modified code is well refactored :)
Let me think how the modified code affect our future work, and then I will decide to merge this commit or not.

**Comment by Red-Portal** [comment]
I personally believe the ranged-for approach is much elegant and straight forward.

**Comment by bethesirius** [comment]
Thanks for your pull request. But, I do not merge it for some reasons.
1. This project doesn't have coding conventions yet.
2. I want to focus improving a functional/performance now.
3. This project also has LineFinder::drawDetectedLines in [linux/src/linefinder.cc](https://github.com/bethesirius/ChosunTruck/blob/master/linux/src/linefinder.cc).

I'm sorry.

**Pull request closed without merging**
