### PR TITLE
refactored LineFinder::drawDetectedLines

### PR DESCRIPTION
**Pull request by Red-Portal**
refactored LineFinder::drawDetectedLines to a ranged-for loop

### CODE REVIEW

**Comment by chi3236** [comment]
The changed code makes compile error

**Comment by Red-Portal** [comment]
What's the version of your compiler? I suppose msvc? Which one?

**Comment by Red-Portal** [comment]
What's the error message?

**Comment by chi3236** [comment]
default
The compiler version is msvc 19.0

**Comment by Red-Portal** [comment]
Ah, can you try to change "auto it2&&" to "auto const& it2" ? That should work

**Pull request closed without merging**
